#!/bin/zsh
# Builds a Sparkle-ready release into dist/release/:
#   4DSTEMExplorer-<version>-<build>.zip  +  4DSTEMExplorerAppcast.xml
#
# Usage:
#   Scripts/make_release.sh                 # builds Release itself
#   Scripts/make_release.sh /path/to.app    # uses an already-built app
#                                           # (the Xcode archive post-action
#                                           #  does this)
#
# The appcast is (re)generated by Sparkle's generate_appcast, which signs the
# zips with the EdDSA key in the login Keychain and keeps entries for any older
# zips still present in dist/release/ — so do not delete them, or users on an
# older version lose their upgrade path.
#
# What is where
# -------------
#   Info.plist  SUFeedURL, SUPublicEDKey, SUEnableAutomaticChecks.
#               NB: the "Increment build" build phase rewrites this file with
#               PlistBuddy on every build, which strips XML comments — hence
#               this note living here rather than beside the keys.
#   Keychain    the EdDSA *private* key, service https://sparkle-project.org,
#               account ed25519, shared with the group's other applications.
#               It is deliberately not in the repository and not in the bucket:
#               it is what stops someone with write access to the bucket from
#               shipping code to every installation.
#
# One-time setup
# --------------
#   Notarisation credentials (needs an app-specific password from
#   account.apple.com):
#     xcrun notarytool store-credentials 4dstem-notary \
#         --apple-id YOUR_APPLE_ID --team-id 67JZ53W5NK
#
#   The bucket must serve the appcast and the zips publicly over HTTPS.
set -euo pipefail
cd "$(dirname "$0")/.."

S3_BUCKET="4dstem-explorer"
S3_BASE="https://${S3_BUCKET}.s3.amazonaws.com"
S3_PROFILE="default"
SIGN_ID="Developer ID Application"
NOTARY_PROFILE="4dstem-notary"
OUT=dist/release
mkdir -p "$OUT"

# A shell invocation may have the CommandLineTools toolchain selected, which
# has no xcodebuild.
xcodebuild -version > /dev/null 2>&1 \
    || export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer

APP=${1:-}
if [[ -z "$APP" ]]; then
    DD=$(mktemp -d /tmp/4dstem-release.XXXXXX)
    echo "building Release..."
    xcodebuild -project "4DSTEM Explorer.xcodeproj" -scheme "4DSTEM Explorer" \
        -configuration Release -derivedDataPath "$DD" build > /dev/null
    APP="$DD/Build/Products/Release/4DSTEM Explorer.app"
fi
[[ -d "$APP" ]] || { echo "app not found: $APP" >&2; exit 1; }

# Work on a copy in /tmp. Never mutate Xcode's archive, and never sign in place
# inside a synced folder, where extended attributes get added underneath you and
# invalidate the signature.
WORK=$(mktemp -d /tmp/4dstem-sign.XXXXXX)
cp -R "$APP" "$WORK/"
APP="$WORK/$(basename "$APP")"

# Anything the syncing left behind will break the seal.
xattr -cr "$APP"

echo "signing with '$SIGN_ID'..."

# Inside out. Notarisation rejects any nested code that is unsigned or lacks
# the hardened runtime, and a signature applied to a container first is
# invalidated by signing its contents afterwards.
#
# --deep is not used: Apple has deprecated it, and it silently skips some
# nested bundles. Everything that needs signing is named here instead, so a
# component that stops being signed shows up as a verification failure rather
# than as a notarisation rejection days later.
SPARKLE="$APP/Contents/Frameworks/Sparkle.framework"
if [[ -d "$SPARKLE" ]]; then
    for nested in \
        "$SPARKLE/Versions/B/XPCServices/Downloader.xpc" \
        "$SPARKLE/Versions/B/XPCServices/Installer.xpc" \
        "$SPARKLE/Versions/B/Updater.app" \
        "$SPARKLE/Versions/B/Autoupdate"; do
        [[ -e "$nested" ]] || continue
        codesign --force --options runtime --timestamp --sign "$SIGN_ID" "$nested"
    done
    codesign --force --options runtime --timestamp --sign "$SIGN_ID" "$SPARKLE"
else
    echo "⚠️  no Sparkle.framework in the app — updates will not work" >&2
fi

# The plugins. They are separate bundles of code and Gatekeeper treats them as
# such: unsigned, the notary service refuses the whole application.
for plugin in "$APP"/Contents/PlugIns/*.bundle(N); do
    codesign --force --options runtime --timestamp --sign "$SIGN_ID" "$plugin"
done

codesign --force --options runtime --timestamp \
    --entitlements "4DSTEM Explorer/4DSTEM Explorer.entitlements" \
    --sign "$SIGN_ID" "$APP"

codesign --verify --strict --verbose=2 "$APP"
echo "signature verified"

VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "$APP/Contents/Info.plist")
BUILD=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$APP/Contents/Info.plist")
ZIP="$OUT/4DSTEMExplorer-${VERSION}-${BUILD}.zip"

ditto -c -k --sequesterRsrc --keepParent "$APP" "$ZIP"

if xcrun notarytool history --keychain-profile "$NOTARY_PROFILE" > /dev/null 2>&1; then
    echo "notarizing (takes a few minutes)..."
    xcrun notarytool submit "$ZIP" --keychain-profile "$NOTARY_PROFILE" --wait
    xcrun stapler staple "$APP"
    # Re-zip so the archive contains the stapled ticket. Without this the
    # download still needs to reach Apple to be verified, and fails offline.
    rm -f "$ZIP"
    ditto -c -k --sequesterRsrc --keepParent "$APP" "$ZIP"
    echo "notarized and stapled"
else
    echo ""
    echo "⚠️  NOT notarized — Gatekeeper will reject downloads."
    echo "   One-time setup (needs an app-specific password from account.apple.com):"
    echo "     xcrun notarytool store-credentials $NOTARY_PROFILE --apple-id YOUR_APPLE_ID --team-id 67JZ53W5NK"
    echo "   then re-run this script."
    echo ""
fi
echo "archived $ZIP"

# Sparkle's tools ship inside the resolved package artifacts, whose path
# depends on whether the package was resolved by SwiftPM or by Xcode.
BIN=""
for candidate in \
    "${DD:-/nonexistent}"/SourcePackages/artifacts/sparkle/Sparkle/bin \
    "$HOME"/Library/Developer/Xcode/DerivedData/4DSTEM_Explorer-*/SourcePackages/artifacts/sparkle/Sparkle/bin \
    .build/artifacts/sparkle/Sparkle/bin; do
    [[ -x "$candidate/generate_appcast" ]] && { BIN="$candidate"; break; }
done
[[ -n "$BIN" ]] || { echo "Sparkle tools not found — build the app once in Xcode first" >&2; exit 1; }

# Release notes.
#
# generate_appcast takes them from a file named after the archive, and the
# archive's name carries the build number — which is not known until the build
# has already happened, since a build phase increments it. So the notes are kept
# under the marketing version, which is decided in advance, and copied into
# place here. A bare HTML fragment (no DOCTYPE, no <body>) is embedded straight
# into the feed as CDATA, so there is no second file to upload and no second URL
# to get wrong.
NOTES="Scripts/release-notes/${VERSION}.html"
if [[ -f "$NOTES" ]]; then
    cp "$NOTES" "$OUT/$(basename "${ZIP%.zip}").html"
    echo "release notes: $NOTES"
else
    echo "⚠️  no release notes at $NOTES — the feed will show this version with none"
fi

"$BIN/generate_appcast" \
    --download-url-prefix "$S3_BASE/" \
    -o "$OUT/4DSTEMExplorerAppcast.xml" \
    "$OUT"

# What to upload is read back out of the feed rather than assumed.
#
# The feed references more than the zip that was just built. Once a second
# version exists, generate_appcast also produces a binary delta — a few hundred
# kilobytes instead of five megabytes — and points the previous version's users
# at it. Listing files by hand here missed exactly that, and a delta that
# returns 404 costs every updating user a failed attempt before Sparkle falls
# back to the full archive.
APPCAST="$OUT/4DSTEMExplorerAppcast.xml"
REFERENCED=("${(@f)$(python3 - "$APPCAST" <<'PY'
import re, sys, urllib.parse
feed = open(sys.argv[1], encoding="utf-8").read()
for url in re.findall(r'<enclosure[^>]*\burl="([^"]+)"', feed):
    print(urllib.parse.unquote(url.rsplit("/", 1)[-1]))
PY
)}")

echo ""
echo "release ready in $OUT/ — upload with:"
for name in "${REFERENCED[@]}"; do
    [[ -n "$name" ]] || continue
    if [[ -f "$OUT/$name" ]]; then
        echo "  aws s3 cp \"$OUT/$name\" \"s3://$S3_BUCKET/\" --profile $S3_PROFILE"
    else
        echo "  ⚠️  the feed references $name, which is not in $OUT/"
    fi
done
echo "  aws s3 cp \"$APPCAST\" \"s3://$S3_BUCKET/\" --profile $S3_PROFILE"
echo ""
echo "the appcast must go up last: it is what points at the archives, and a feed"
echo "naming a file that is not there yet fails every running copy's check."
echo ""
echo "shareable download link:"
echo "  $S3_BASE/$(basename "$ZIP")"
